# Generated by Django 4.2.2 on 2023-07-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
