# Generated by Django 4.2.2 on 2023-07-24 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
        ('produto', '0004_produto_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.marca'),
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
